services:
  amorequest:
    build:
      context: ./amorequest
    container_name: amorequest
    volumes:
      - ./amorequest:/var/www/html
    working_dir: /var/www/html
    networks:
      - devnet

  nginx:
    image: nginx:alpine
    container_name: dev-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - devnet

  validator:
    build:
      context: ./lead-validator
    container_name: lead-validator
    volumes:
      - ./lead-validator:/var/www/html
    working_dir: /var/www/html
    networks:
      - devnet


networks:
  devnet:
    external: true # ⬅️ Docker не создаёт сеть, а использует общую